name: GPTLint

on: pull_request

jobs:
  gptlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitLint and dependencies
        run: |
          pip install gitlint openai

      - name: Run GPTLint with custom rule
        run: |
          gitlint --extra-path lint-rules/gpt_lint_rule.py
