name: GPT Security Linter

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  security-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run GPT Security Linter
        run: |
          # Get changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          
          # Iterate through each changed file
          for FILE in $CHANGED_FILES; do
            # Send the file content to GPT for security analysis
            CONTENT=$(cat $FILE)
            RESPONSE=$(curl -X POST https://api.openai.com/v1/completions \
              -H "Authorization: Bearer $OPENAI_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{
                "model": "gpt-4",
                "prompt": "Are there any security risks in the following code? '$CONTENT'. Answer in JSON format...",
                "max_tokens": 1000
              }')

            # Parse and handle the JSON response
            echo "Response for $FILE: $RESPONSE"
            # Optionally, add GitHub comments or block the PR if issues are found
          done
