name: GPT Security Linter

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  security-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Get changed files
        run: |
          # Use `github.event.before` if available, fallback to HEAD^ if not
          if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]; then
            # First commit or new branch PR
            BASE_COMMIT=$(git rev-parse HEAD^)
          else
            BASE_COMMIT=${{ github.event.before }}
          fi

          # Fetch changes between the base commit and current commit
          CHANGED_FILES=$(git diff --name-only $BASE_COMMIT ${{ github.sha }})

          # Display changed files for debugging
          echo "Changed files: $CHANGED_FILES"

      - name: Run GPT Security Linter
        run: |
          for FILE in $CHANGED_FILES; do
            # Send the file content to GPT for security analysis
            CONTENT=$(cat $FILE)
            RESPONSE=$(curl -X POST https://api.openai.com/v1/completions \
              -H "Authorization: Bearer $OPENAI_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{
                "model": "gpt-4",
                "prompt": "Are there any security risks in the following code? '$CONTENT'. Answer in JSON format...",
                "max_tokens": 1000
              }')

            # Parse and handle the JSON response
            echo "Response for $FILE: $RESPONSE"
            # Optionally, add GitHub comments or block the PR if issues are found
          done
